version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./.env

  rsschool:
    image: rs:latest
    restart: always
    container_name: rsschool
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  postgres: